---
title: "makePackage"
author: "J Grembi"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
pkgName <- "riskCommunicator"

pkgFilePath <- "/Users/JGrembi/Dropbox/riskCommunicator R package/package/"
library(utils)
myself <- utils::person(given = "Jessica",
                        family = "Grembi",
                        email = "jgrembi@stanford.edu",
                        role = c("aut", "cre"),
                        comment = "")

## My options for dev
myself_at_r <- paste0(
    "person(given = ",
    deparse(myself$given),
    ", family = ",
    deparse(myself$family),
    ", role = ",
    deparse(myself$role),
    ", email = ",
    deparse(myself$email),
    ")"
)

options(
    devtools.desc.author = myself_at_r,
    devtools.desc.license = "GPL (>= 2)"
)



usethis::create_package(path = paste0(pkgFilePath ,pkgName), rstudio = F)
setwd(pkgFilePath)
devtools::document(pkg = paste0(pkgFilePath, pkgName))
setwd(pkgFilePath)
devtools::install(pkg = paste0(pkgFilePath, pkgName))

riskComm.check <- devtools::check(pkg = pkgName)

devtools::build(pkg = paste0(pkgFilePath, pkgName))
```


```{r}
'usethis::use_testthat':
     Add testing infrastructure to a package that does not already have
     it. This will create ‘tests/testthat.R’, ‘tests/testthat/’ and add
     ‘testthat’ to the suggested packages. This is called automatically
     from ‘test’ if needed.

'usethis::use_test':
     Add a test file, also add testing infrastructure if necessary.
     This will create ‘tests/testthat/test-<name>.R’ with a
     user-specified name for the test.  Will fail if the file exists.

'usethis::use_vignette':
     Adds needed packages to ‘DESCRIPTION’, and creates draft vignette
     in ‘vignettes/’. It adds ‘inst/doc’ to ‘.gitignore’ so you don't
     accidentally check in the built vignettes.

'usethis::use_rcpp':
     Creates ‘src/’ and adds needed packages to ‘DESCRIPTION’.
```

```{r}
usethis::use_vignette("LongVignette")
```

